### ISSUE TITLE
partition usage

### ISSUE THREAD

**Issue by portokalh** [LudvigOlsen/groupdata2#5]
thank you for sharing your work.
i have tried to use partition with a 24 element data frame as 25%/75% 
parts <- partition(mydfb, p = c(0.25), id_col = "mysubject_index", cat_col = 'mygenotype')
mydfb
   mysubject_index mygenotype
1                1          1
2                2          1
3                3          0
4                4          0
5                5          0
6                6          0
7                7          0
8                8          1
9                9          1
10              10          1
11              11          0
12              12          1
13              13          1
14              14          1
15              15          1
16              16          1
17              17          0
18              18          0
19              19          1
20              20          0
21              21          0
22              22          0
23              23          0
24              24          0
and i am surprised to see that it produces a 5 element  test_set, and and a 19 element train_set
> test_set <- parts[[1]]
> train_set <- parts[[2]]
> test_set  %>% kable()
> train_set %>% kable()

| mysubject_index| mygenotype|
|---------------:|----------:|
|               4|          0|
|               6|          0|
|              18|          0|
|              12|          1|
|              15|          1|
| mysubject_index| mygenotype|
|---------------:|----------:|
|               3|          0|
|               5|          0|
|               7|          0|
|              11|          0|
|              17|          0|
|              20|          0|
|              21|          0|
|              22|          0|
|              23|          0|
|              24|          0|
|               1|          1|
|               2|          1|
|               8|          1|
|               9|          1|
|              10|          1|
|              13|          1|
|              14|          1|
|              16|          1|
|              19|          1|

It is possible that i am using it wrong, or maybe there is an offset by 1 somewhere?
Many thanks,
Alex

**Comment by LudvigOlsen** [comment]
Hi Alex, @portokalh

It depends on what you want. If you just want a (possibly unbalanced) random split, you shouldn't use the id_col and cat_col, e.g.:

```{R}
test_data <- data.frame("mysubject_index"=1:24,
                        "mygenotype"=factor(c(1,1,0,0,0,0,0,1,1,1,0,1,1,1,1,1,0,0,1,0,0,0,0,0)))

test_data%>% 
  partition(p=0.25, list_out = F) %>%   # list_out=FALSE is just for keeping it in one DataFrame
  count(.partitions) 
```
|.partitions |  n|
|:-----------|--:|
|1           |  6|
|2           | 18|

Here you see, that it correctly puts 6 rows in the first partition.

When you add the cat_col and/or id_col, the behavior changes.
cat_col first splits the dataset by the categorical column, partitions each one, and merge them again.

E.g. you have a different number of rows per class:

```{r}
test_data %>% 
  count(mygenotype)
```
|mygenotype |  n|
|:----------|--:|
|0          | 13|
|1          | 11|

So first class 0 is partitioned, resulting in 3 and 10 rows per partition.
Then class 1 is partitioned, resulting in 2 and 9 rows per partition (it is flooring the division, e.g. 11/4 = 2.75 = 2).

|mygenotype |.partitions |  n|
|:----------|:-----------|--:|
|0          |1           |  3|
|0          |2           | 10|
|1          |1           |  2|
|1          |2           |  9|

The upside is, that you will get ~25% of the 0's and ~25% of the 1's. If you don't use cat_col, it could be a different mix, e.g. ~30% 0's and ~18% 1's. So there's potentially a different balance between the two classes in the two partitions.

A sidenote is that you don't gain anything from using id_col, if you only have one observation per ID. It's meant for putting all observations of an ID into the same partition. Which happens automatically, when there's only one per ID :) If there were big differences between the number of observations per ID, it could also return partitions very far from an overall 25/75 split. But that's often worth it, if you want to avoid leakage between train/test sets or similar.

Hope this helps :)

**Comment by portokalh** [comment]
this is great, thank you!
